### PR TITLE
Spherical

### PR DESCRIPTION
**Pull request by AleksiNummelin**
Changes to allow for the decomposition to work on spherical geometry. The main changes are the addition of a new utility function, a new type of grid (i.e. spherical grid), and a new test function. The spherical geometry is computationally demanding and is therefore done in parallel.

The code is also Python 3 compatible, and there are few more parameters that can be given. For example, for model based application, I would suggest using model defined divergence and curl rather than calculating them from the velocity output (if the model is defined on a c-grid, the curl and divergence will not be correctly calculated).

### CODE REVIEW

**Comment by pswpswpsw** [comment]
@AleksiNummelin  just curious, if it was on a sphere, then it becomes naturally periodic. Then is it possible to just use fast Fourier transform to get the HHD decomposition? 

https://en.wikipedia.org/wiki/Helmholtz_decomposition#Another_derivation_from_the_Fourier_transform

**Comment by AleksiNummelin** [comment]
@pswpswpsw I should have been more specific. It is indeed rather straightforward to do the decomposition on a connected spherical domain as you point out (there are many excellent python implementations for that). However, here we were interested in the HHD on a spherical domain that is disconnected i.e. global ocean that has continents that break the periodicity.

This algorithm makes then an approximate HHD by using a Green's function on a sphere (see the papers by Harsh and others for details). Basically, the success of the method boils down to the fact that it is the local div and curl that are most important for the decomposition and the far-field not so much. However, this is still not truly accurate since the Green's function we use is meant for a connected spherical domain while one would actually need to derive the Green's function for a disconnected sphere by running an ocean model (basically, one would need to use the velocity field that one is about to decompose to derive the Green's functions). Anyhow, for our purposes the approximate decomposition produces accurate enough results, which we again attribute to the nature of the flow (i.e the local div and curl dominate).

Hope that helps, let me know if you want to try it out. If you have a connected spherical domain (i.e. atmosphere) then there are other FFT based implementations that are more suitable.

**Comment by pswpswpsw** [comment]
@AleksiNummelin Yes! Exactly. Thanks for the quick reply! I agree with you on using geometry-specific Green function and the boundary conditions for the EXACT HHD decomposition. 

However, I think the issue here is, even you have Green function (which is easy to get for any geometry since it is just solving a large linear system), if you follow the formula of convoluting over the whole domain, that becomes a O(N^3) computation which is not tractable in 3D large datasets (1024^3 for example), is it? But yes, if you application is 2D, then it is fine.

**Comment by pswpswpsw** [comment]
By the way, for your information, I found this paper currently describes they way of the state of the art in fluid mechanics community doing HHD in any large datasets with a solid surface for boundary condition, 

https://www.cambridge.org/core/services/aop-cambridge-core/content/view/CFCAF1F7636B1A21654EB7268AB849FC/S0022112009993156a.pdf/on_the_dynamical_relevance_of_coherent_vortical_structures_in_turbulent_boundary_layers.pdf

**Comment by AleksiNummelin** [comment]
Thanks for the reference. We were interested in 2D surface problem here - 3D would blow up the computation. Also, as far as I recall, there is no scalar streamfunction in 3D. For large scales in the ocean one could apply something similar on constant density surfaces and the errors should be still small (velocities across density surfaces are usually much smaller than along the density surfaces)

**Comment by bhatiaharsh** [comment]
@AleksiNummelin. Thank you very much for adding this.

This PR needs some changes though, because the old code seems to break. I am going to handle this in two parts -- merge to a different base, then fix the issues, and merge to master again.

**Comment by bhatiaharsh** [comment]
@AleksiNummelin. I have created a new commit to fix a few issues from this PR, and added to a branch "spherical". 

I can get the old code to work, but for the new test, I see nan's in the scalar potentials. I do see a lot of divide by zero errors. I havent had a chance to look at the code in greater detail. Although the streamfunctions display correctly (see the new jupyter notebook). What is the purpose of the scaling by 1E6?

**Pull request merged**
